# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageApp
  pod 'ReachabilitySwift'

  target 'ImageAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
